set(TORRENT_BUILDER_VERSION "2.0.0-rc1")
include(${CMAKE_CURRENT_LIST_DIR}/../../cmake/version.cmake)
if(NOT TORRENT_BUILDER_DISPLAY_VERSION STREQUAL "2.0.0-rc1")
    message(FATAL_ERROR "FAIL: DISPLAY_VERSION should be 2.0.0-rc1, got: ${TORRENT_BUILDER_DISPLAY_VERSION}")
endif()
if(NOT TORRENT_BUILDER_VERSION STREQUAL "2.0.0")
    message(FATAL_ERROR "FAIL: VERSION should be 2.0.0 (sanitized), got: ${TORRENT_BUILDER_VERSION}")
endif()
message(STATUS "PASS: version pre-release sanitized")
